---
title: "Week 11 Assignment"
author: "Patrick Voorhies"
date: "11/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Package Installation
library(tidyverse)
library(modelr)
library(caret)
library(tictoc)


#Load the data
load("pd.Rdata")

```

#Question 1: Create a 10-fold cross validation 

```{r}

load("pd.Rdata")
pd<-pd%>%
  select(median_home_val,median_hh_inc,coll_grad_pc,homeown_rate,per_capita_inc)%>%
  mutate_all(funs(as.numeric))%>%
  mutate(home_rank=percent_rank(median_home_val))%>% 
  tbl_df()

## Define the model
mod1_formula<-formula(home_rank~coll_grad_pc+
                        per_capita_inc)
## Run the model against all of the data
basic.mod<-lm(mod1_formula,
              data=pd); summary(basic.mod)


pd_cf<-pd%>%
crossv_kfold(10)
pd_cf

tic()
rmse_mod1<-pd_cf %>%
mutate(train = map(train, as_tibble)) %>% ## Convert to tibbles 
  mutate(model = map(train, ~ lm(mod1_formula,
data = .))) %>%
mutate(rmse = map2_dbl(model, test, rmse)) %>% ## apply model, get rmse
  select(.id, rmse) ## pull just id and rmse
toc()

summary(rmse_mod1$rmse)
gg<-ggplot(rmse_mod1,aes(rmse)) 
gg<-gg+geom_density()
gg

```


#Question 2: Using a random partition, create 100 separate cross validations 

```{r}
pd_cv<-pd%>%
  crossv_mc(n=1000,test=.2) 
pd_cv

tic()
mod1_rmse_cv<-pd_cv %>%
mutate(train = map(train, as_tibble)) %>% ## Convert to tibbles 
  mutate(model = map(train, ~ lm(mod1_formula, data = .)))%>% 
  mutate(rmse = map2_dbl(model, test, rmse))%>%
select(.id, rmse) ## pull just id and rmse
mod1_rmse_cv 
toc()

summary(mod1_rmse_cv$rmse)

gg<-ggplot(mod1_rmse_cv,aes(rmse))

gg<-gg+geom_density(bins=50,fill="blue",alpha=.2) 

gg

```


